# Generated by Django 5.2.8 on 2025-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinician',
            old_name='on_duty',
            new_name='duty_status',
        ),
        migrations.AlterField(
            model_name='clinician',
            name='specialization',
            field=models.CharField(choices=[('general', 'General Doctor'), ('dentist', 'Dentist'), ('pediatric', 'Pediatrician'), ('cardiology', 'Cardiologist'), ('dermatology', 'Dermatologist'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
