# Generated by Django 5.2.8 on 2025-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0002_rename_on_duty_clinician_duty_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='full_name',
            field=models.CharField(default='unknown clinician', max_length=100),
        ),
        migrations.AddField(
            model_name='clinician',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='duty_status',
            field=models.CharField(choices=[('On Duty', 'On Duty'), ('Off Duty', 'Off Duty')], default='Off Duty', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='specialization',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('Gynecology', 'Gynecology'), ('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Psychiatry', 'Psychiatry'), ('Dentistry', 'Dentistry')], max_length=50),
        ),
    ]
